/**
 * @fileoverview gRPC-Web generated client stub for product
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.20.1
// source: proto/product.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.product = require('./dashboard/proto/product_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.product.ProductViewServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.product.ProductViewServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.product.ProductViewRequest,
 *   !proto.product.ProductViewResponse>}
 */
const methodDescriptor_ProductViewService_SendProductView = new grpc.web.MethodDescriptor(
  '/product.ProductViewService/SendProductView',
  grpc.web.MethodType.UNARY,
  proto.product.ProductViewRequest,
  proto.product.ProductViewResponse,
  /**
   * @param {!proto.product.ProductViewRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.product.ProductViewResponse.deserializeBinary
);


/**
 * @param {!proto.product.ProductViewRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.product.ProductViewResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.product.ProductViewResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.product.ProductViewServiceClient.prototype.sendProductView =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/product.ProductViewService/SendProductView',
      request,
      metadata || {},
      methodDescriptor_ProductViewService_SendProductView,
      callback);
};


/**
 * @param {!proto.product.ProductViewRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.product.ProductViewResponse>}
 *     Promise that resolves to the response
 */
proto.product.ProductViewServicePromiseClient.prototype.sendProductView =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/product.ProductViewService/SendProductView',
      request,
      metadata || {},
      methodDescriptor_ProductViewService_SendProductView);
};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.product.DashboardServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.product.DashboardServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.product.StreamRequest,
 *   !proto.product.ProductRating>}
 */
const methodDescriptor_DashboardService_StreamTopProducts = new grpc.web.MethodDescriptor(
  '/product.DashboardService/StreamTopProducts',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.product.StreamRequest,
  proto.product.ProductRating,
  /**
   * @param {!proto.product.StreamRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.product.ProductRating.deserializeBinary
);


/**
 * @param {!proto.product.StreamRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.product.ProductRating>}
 *     The XHR Node Readable Stream
 */
proto.product.DashboardServiceClient.prototype.streamTopProducts =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/product.DashboardService/StreamTopProducts',
      request,
      metadata || {},
      methodDescriptor_DashboardService_StreamTopProducts);
};


/**
 * @param {!proto.product.StreamRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.product.ProductRating>}
 *     The XHR Node Readable Stream
 */
proto.product.DashboardServicePromiseClient.prototype.streamTopProducts =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/product.DashboardService/StreamTopProducts',
      request,
      metadata || {},
      methodDescriptor_DashboardService_StreamTopProducts);
};


module.exports = proto.product;

